server {
  listen 8965;

  client_max_body_size 100000m;

  location /data/ {
    alias /data/;

    add_header Accept-Ranges bytes;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';

    expires 1y;
    add_header Cache-Control "public, immutable";

    mp4;
    mp4_buffer_size 1m;
    mp4_max_buffer_size 5m;
  }

  location /api/auth/ {
    proxy_pass http://client:3000/api/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ {
    proxy_pass http://api:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_read_timeout 300s;
    proxy_connect_timeout 75s;
  }

  location / {
    proxy_pass http://client:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
